rem a script to generate C# code from XSD D20A

xsd CrossIndustryOrder_18p1.xsd ^
	ReusableAggregateBusinessInformationEntity_27p0.xsd ^
	QualifiedDataType_27p0.xsd ^
	UnqualifiedDataType_27p0.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_AccessRightsType_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_AccountingAccountBalanceReopeningType_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_AccountingAccountClassification_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_AccountingAccountNatureType_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_AccountingAccountStatus_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_AccountingAccountType_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_AccountingAmountQualifierType_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_AccountingAmountType_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_AccountingContact_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_AccountingDocumentType_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_AccountingEntryCategory_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_AccountingEntryLineCategory_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_AccountingEntryLineSource_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_AccountingEntryProcessing_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_AccountingJournalCategory_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_AccountingJournal_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_AccountingPeriodFunctionType_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_AccountingPerquisite_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_AccountingVoucherMedium_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_AdditionalPostponement_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_AddressFormatType_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_AlternateCurrencyAmount_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_AmortizationMethod_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_AmountWeightType_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_CertificateType_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_FinancialAccountType_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_FinancialInstitutionRole_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_LifetimeEndCost_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_OrganizationFunctionType_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_PartyType_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_RefundMethod_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_ScenarioType_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_SoftwareUserType_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\EDIFICAS-EU_TaxExemptionReason_D11A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\IANA_CharacterSetCode_2013-01-23.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\ISO_ISO2AlphaLanguageCode_2006-10-27.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\ISO_ISO3AlphaCurrencyCode_2012-08-31.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_ActionCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_AddressType_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_AdjustmentReasonDescriptionCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_AdjustmentReasonDescriptionCode_Financial_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_AgencyIdentificationCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_AllowanceChargeIdentificationCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_AllowanceChargeReasonCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_AutomaticDataCaptureMethodCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_CargoOperationalCategoryCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_CargoTypeClassificationCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_CargoTypeCode_1996Rev2Final.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_CharacterSetEncodingCode_40106.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_CommodityIdentificationCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_CommunicationMeansTypeCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_ContactFunctionCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_ContractorType_D10B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_ContractTypeCode_D10B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_CostManagementCode_D10B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_CostReportingCode_D10B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_DangerousGoodsPackingCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_DangerousGoodsRegulationCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_DeliveryPlanCommitmentLevelCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_DeliveryTermsCode_2010.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_DimensionTypeCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_DocumentNameCode_Accounting_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_DocumentNameCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_DocumentNameCode_Invoice_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_DocumentNameCode_Quotation_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_DocumentNameCode_Remittance_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_DocumentNameCode_Scheduling_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_DocumentStatusCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_DutyorTaxorFeeCategoryCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_DutyTaxFeeTypeCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_EarnedValueCalculationMethod_D10B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_EquipmentSizeTypeDescriptionCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_EventTimeReferenceCodePaymentTermsEvent_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_EventTimeReferenceCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_FreightChargeQuantityUnitBasisCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_FreightChargeTariffCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_FundingTypeCode_D10B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_GoodsTypeCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_GoodsTypeExtensionCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_GovernmentActionCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_HierarchicalStructureTypeCode_D10B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_LocationFunctionCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_MarkingInstructionCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_MeasuredAttributeCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_MeasurementUnitCommonCodeDuration_4.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_MeasurementUnitCommonCodeLinear_4.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_MeasurementUnitCommonCodeTemperature_4.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_MeasurementUnitCommonCodeVolume_4.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_MeasurementUnitCommonCodeWeight_4.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_MeasurementUnitCommonCode_Airflow_4.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_MeasurementUnitCommonCode_FileSize_4.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_MessageFunctionCode_Acknowledgement_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_MessageFunctionCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_PackageTypeCode_2006.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_PackagingLevelCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_PackagingMarkingCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_PartyRoleCode_ChargePaying_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_PartyRoleCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_PaymentGuaranteeMeansCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_PaymentMeansChannelCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_PaymentMeansCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_PaymentMethodCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_PaymentTermsTypeCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_PlanningLevel_D10B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_PriceTypeCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_PriorityDescriptionCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_ProcessTypeCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_ProjectTypeCode_D10B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_ReferenceTypeCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_ReportingThresholdTriggerType_D10B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_ResourceCostCategory_D10B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_ResourcePlanMeasureType_D10B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_ResponseTypeCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_ScheduleTaskRelationshipType_D10B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_ScheduleTaskType_D10B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_ScheduleTypeCode_D10B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_SealConditionCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_SealingPartyRoleCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_SealTypeCode_D14A.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_SecurityClassificationType_D10B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_StatusCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_StatusDescriptionCode_AccountingDebitCredit_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_StatusDescriptionCode_Workflow_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_TemperatureTypeCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_TimeOnlyFormatCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_TimePointFormatCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_TransportEquipmentCategoryCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_TransportEquipmentFullnessCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_TransportMeansTypeCode_2007.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_TransportModeCode_2.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_TransportMovementStageCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Research_about_CII\D20A\uncefact\codelist\standard\UNECE_TransportPaymentArrangementCode_D19B.xsd ^
	D:\COMPANY\Customers\Billit\Project_CII\XSD\D20A\uncefact\identifierlist\standard\ISO_ISOTwo-letterCountryCode_SecondEdition2006.xsd ^
	D:\COMPANY\Customers\Billit\Project_CII\XSD\D20A\uncefact\identifierlist\standard\UNECE_FreightCostCode_4.xsd ^
	D:\COMPANY\Customers\Billit\Project_CII\XSD\D20A\uncefact\identifierlist\standard\UNECE_PaymentTermsDescriptionIdentifier_D19B.xsd ^
	 /c